sendou-ink/sendou.ink

.gitignore
Related to #85. Right now, running `npm run cy:run` creates output screenshots and/or videos that might accidentally get committed to Git.
=> Ignore test run output from Cypress

components/layout/IconNavBar.tsx, pages/_app.tsx
#388 
It allows to ignore chakra-ui variable for width (20rem) and use width depending on content size.
Also `min-width: max-content` can be useful if smth goes wrong with this solution.
=> Unset width for popover in navigation

components/builds/APStats.tsx, components/common/AbilityIcon.tsx, hooks/builds.ts
I can't always remember what each icon is for the ability chunks (mostly on the build analyzer page) so I'm adding a title to the `Image` component in `AbilityIcon` so on hover some helper text appears with the full name of the ability.
This also improves the type definitions and provides a slight accessibility improvement as well.
Pull down and verify pages that utilize the `AbilityIcon` component shows the name of the ability on hover.
=> Add title to ability icon as helper text

components/common/NewTable.tsx, components/maps/MapPoolDisplay.tsx, pages/maps.tsx
This PR adds an alternate method of displaying the map pool.
I was tasked with creating a [map pool graphic](https://cdn.discordapp.com/attachments/722960400831873105/862796200897150976/lowinkmaps-jul21.png) based off a screenshot from the s.ink map list generator, which I found mildly annoying due to the way the map pool is displayed.
=> Maplist generator: Add option to display map pool as table

app/routes/u.$identifier/builds/new.tsx
#946 
Looks like empty array is enough to be controlled after init and be empty so required trigger alert for input.
Empty onChange is because otherwise it will give another error in console (and readonly doensn't work in this case). Maybe it could be done in a better way.
=> Other default value + empty onChange

public/locales/da/common.json, public/locales/da/contributions.json, public/locales/da/front.json, translation-progress.md
Added Translations for the missing lines in the following json.files.
The lines are placed, so the correspond with the English location files.
**common.json**
1. pages.analyzer
**contributions.json**
1. translation
**front.json**
1. analyzer.description
=> Adding of Missing Danish translations.

app/components/Ability.tsx, app/styles/common.css
`<Ability/>` can now be tabbed through, and it now shares the same focus outline, hover, and mousedown styles with `<AbilitiesSelector/>`. This includes the `cursor: pointer` style that makes it more obvious that this component is clickable like other buttons.
Fixes #894.
Before:
https://user-images.githubusercontent.com/3038600/192218613-2754506e-520b-4629-b35c-5440afac3b0e.mov
After:
https://user-images.githubusercontent.com/3038600/192218785-8e40da09-d512-47fe-9341-bcee18c213be.mov
=> Make `<Ability/>` support keyboard navigation

public/locales/da/front.json
Added the missing Danish translation in the front.json file.
Added "buildsGoTo"
Slightly changed translation of  "plus.description":
=> Danish Tranlsation

app/components/AbilitiesSelector.tsx, app/components/Ability.tsx, app/components/Image.tsx, app/styles/common.css
- Do not allow dragging an ability onto a slot that cannot accept that ability.
- When dragging, dim slots that are not a valid target for the ability currently being dragged.
- Do not make any changes to the existing click behavior to assign abilities.
This addresses #82 but I don't know if this closes it: this PR does not implement the bonus idea of holding shift to duplicate abilities across slots. That should be possible, but we would likely have to use a drag/drop library and not necessarily the native drag and drop API (which is what this PR relies on). I think this might add a bit of complexity.
Possible area for further improvement: add the ability to drag a placed ability (one already assigned to a slot) from one slot to another. I can make an issue if this is something you would …
=> Add ability to drag abilities into slots

app/components/Ability.tsx, app/components/BuildCard.tsx, app/styles/common.css
Fix issue where abilities appeared clickable when they were not by adding a `readonly` attribute set on for instances of `<Ability/>` in `<BuildCard/>`.
Issue was introduced in #971.
Fixes #981
https://user-images.githubusercontent.com/3038600/193729074-36cbe7da-c34e-446f-9986-8e6a3cdb8143.mov
=> Fix issue where abilities appeared clickable when they were not

app/styles/common.css
fixes #993
Seems like it's caused by the browser's default font size. The ability card gets too small for the fixed width images.
=> Use fixed widths for BuildCard

app/modules/i18n/config.ts
As talked about in the ticket, the interpolation escaping i18next provides is not beneficial in combination with React in this case.
Fixes #994
=> Deactivate i18next interpolation escaping

app/routes/u.$identifier/results.tsx, app/styles/u.css, public/locales/de/user.json, public/locales/en/user.json, translation-progress.md
Closes #864 
Notes:
- ~~The `check-translation-jsons` script already found changes on the current head, which is why there are two commits with changes to `translation-progress.md`.~~ Fixed after rebase
- Since the table became wider with this change I checked some smaller viewports and noticed that the scroll on overflow was broken for the table, so I fixed this by making sure the `main` element is normally just as wide as the parent.
=> Add participant count in user page results table

app/routes/badges/$id/edit.tsx
Closes #826
To be honest, I'm not a 100% sure how the CSS caused the glitched behaviour.
However, the reason why this modal was behaving different than the others, is that the "stack md" classes were applied to the dialog itself, instead of the container inside.
I assume the blame then goes to the css overwriting the dialog's `display: block` with `display: flex`.
=> Fix edit badge dialog flickering

app/components/Breadcrumbs.tsx, app/root.tsx, app/routes/analyzer.tsx, app/routes/badges.tsx, app/routes/builds.tsx, app/routes/builds/$slug.tsx, app/routes/builds/index.tsx, app/routes/calendar/$id/index.tsx, app/routes/calendar/$id/report-winners.tsx, app/routes/calendar/index.tsx, app/routes/calendar/new.tsx, app/routes/contributions.tsx, app/routes/faq.tsx, app/routes/index.tsx, app/routes/maps.tsx, app/routes/object-damage.tsx, app/routes/u.$identifier.tsx, app/routes/u.$identifier/builds/index.tsx, app/routes/u.$identifier/builds/new.tsx, app/routes/u.$identifier/index.tsx, app/styles/builds.css, app/styles/common.css, app/utils/arrays.ts, app/utils/remix.ts
I saw this in the Remix docs as an example for using the handle export and thought this would probably be cool to implement :)
It's probably easiest to look at the two commits separately
=> Generic Breadcrumbs component/mechanism

app/components/layout/index.tsx
https://github.com/Sendouc/sendou.ink/issues/1043
Issue 1043: changed `<div>` tag to `<h1>` tag for semantic HTML on the top-most UI buttons for an active page
The buttons look exactly the same before & after the change based on my testing =)
=> Issue 1043: changed <div> tag to <h1> tag for semantic HTML for top-most UI buttons on active page

app/components/Combobox.tsx
https://github.com/Sendouc/sendou.ink/issues/914
Passed a FUSE_OPTIONS object to the Fuse() object.
- We can now adjust how "strict" the search is.
- We currently only adjust the `threshold` attribute of the FUSE_OPTIONS object
With a `threshold` value of 0.42, this is what the search result looks like:
I tried with `threshold: 0.45` and it still gave more than 1 result, so I figured 0.42 is a good `threshold` value to start with.
Docs for Fuse Options: https://fusejs.io/api/options.html
=> UserComboBox is now more strict

app/routes/u.$identifier/edit.tsx
Manually sending a request currently allows users to input anything that is 4 characters as their discrim which can be seen [here](https://sendou.ink/u/illya). I have added a simple check to make sure this is no longer possible.
=> Only allow numbers as discrim

app/components/layout/LanguageChanger.tsx
Closes #1096 
This fixes the issue, but it feels a little bit brute-force. I'm not sure what a better solution would be 🤔 
I guess one option would be not to use links at all, but to persist the language using a fetch/form and then somehow invalidate the root loader cache? (possibly by still setting the search param programatically, or maybe there is another option)
=> Make LanguageChanger respect existing search params

README.md
Updated README with `npm run cf` steps & also a git command that will fix a line ending error
=> Updated README with `npm run cf` steps & also a git command that will fix a line ending error

app/components/Placement.tsx, app/utils/strings.ts, public/locales/da/common.json, public/locales/de/common.json, public/locales/en/common.json, public/locales/es-ES/common.json, public/locales/es-US/common.json, public/locales/fr/common.json, public/locales/nl/common.json, scripts/check-translation-jsons.ts, translation-progress.md
Closes #1016 
I hope the creative use of `^` to detect superscript is fine. Pretty sure there are no languages that show "1^ place" 😅 
I tried adding some translations for languages where I could find a clear answer.
References: https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html + google results on "\<language\> rank ordinal suffix" or similar.
Unfortunately the unicode comparison alone doesn't go into detail in regards to grammatical gender. In some cases the grammatical gender of the described object changes the suffix, but in most cases this should then get the same gender as the translation for "place".
=> Add placement ordinal translation

app/routes/calendar/$id/index.tsx
https://github.com/Sendouc/sendou.ink/issues/1115
Fixed "Map Pool" title on active event pages to use the appropriate localization value
=> Fixed "Map Pool" title in events to use the appropriate localization value

app/components/Button.tsx
https://github.com/Sendouc/sendou.ink/issues/1134
External links are now opened in a new tab.
- Done via adding the HTML attribute `target="_blank"` to the `<a />` tag for external links
- Note that `rel="noreferrer"` is needed to pass an ESLint check due to security concerns
Opening links in a new tab in React: https://bobbyhadz.com/blog/react-open-link-in-new-tab#open-a-link-in-a-new-tab-in-react
`rel="noreferrer"` attribute & security vulnerabilities if you don't include it: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md
=> External links are now opened in a new tab

app/components/MapPoolSelector.tsx, app/routes/calendar/new.tsx, app/routes/maps.tsx, app/routes/to.$identifier/index.tsx
I also refactored the `noTitle` prop away by not falling back to a default. Mainly to avoid confusion when e.g. setting `title` and `noTitle` together, and because I think not setting a title is a nicer API for not showing one.
=> Re-enable bulk edit controls for maplist pools when logged out

app/styles/common.css
https://github.com/Sendouc/sendou.ink/issues/1141
Temporary solution for dropdown arrow in `<select />` elements for Light Mode.
I had to use a `.light select {}` CSS selector to do this at the moment, since there are some challenges in passing CSS vars to SVGs if they are used in a `background-image` CSS property. It most likely isn't the best solution, but IMO it's an acceptable one for the time being.
As for the color used, it's just `(0, 0, 0)` with 55% transparency - the exact same analog to the current setting being used for dark mode, `(255, 255, 255)` with 55% transparency
=> Temporary solution for dropdown arrow in `<select />` elements for Light Mode

app/routes/analyzer.tsx
https://github.com/Sendouc/sendou.ink/issues/1053
Fixed a flicker issue with the Weapon Combobox component.
To fix this, I've added `unstable_shouldReload()` in `app\routes\analyzer.tsx`.
To replicate the bug reliably in the live version of the website, I enabled low-end mobile throttling in my Google Chrome's web browser debugging tools. By doing this, I can visibly see the flicker every time I change my search selection in the Weapon Combobox.
I did the same thing after implementing my fix on the locally hosted application & could no longer replicate this issue.
- Remix docs with regards to the `unstable_shouldReload()` function https://remix.run/docs/en/v1/api/conventions#never-reloading-the-root
- Discussion on the Remix Github project that talks about this issue: …
=> Fixed flicker with combobox issue using unstable_shouldReload()

app/styles/calendar.css
https://github.com/Sendouc/sendou.ink/issues/935
https://github.com/Sendouc/sendou.ink/issues/1117
Fixed Calendar WeekLink element CSS styling by adjusting height & min-height dynamically
- I believe this same change also fixed calendar week link element widths not being symmetric for the left-most and right-most elements (likely due to the auto-scaling)
I briefly tested this fix for all languages & at a reasonably-sized phone width in the web browser dev tools tab (at a width of 375px) for a small phone, and everything lines up well. I also briefly scrolled left and right a reasonably sane amount to check that there weren't any obvious edge cases.
- Full size, French: 
- Full size, English: 
- Full size, Japanese: 
- Full size, Russian: 
- Small phone size, French: 
- Small phone size, …
=> Fixed Calendar WeekLink element CSS styling

app/modules/analyzer/abilityChunksCalc.test.ts, app/modules/analyzer/abilityChunksCalc.ts, app/routes/analyzer.tsx
https://github.com/Sendouc/sendou.ink/issues/1180
Ability chunk calculations now properly takes Ability Doubler into account
- Ability Doubler ability in of itself does not contribute towards ability chunk count.
- For the Clothing gear, if it has Ability Doubler, then the cost of adding a non-duplicate secondary (sub) ability only costs 3 ability chunks. Reference: https://splatoonwiki.org/wiki/Splatfest_Tee#Splatoon_3_2
- Build Analyzer also no longer shows Ability Doubler as an Ability Chunk entry, nor does it show the Ability Chunks accordion if Ability Doubler is the only selected ability in the build
I also added some unit tests to make sure that Ability Chunk calculations are behaving as intended when Ability Doubler is present on the Clothing gear.
Screenshot of passing unit tests …
=> Ability chunk calculation now properly takes Ability Doubler into account

app/routes/u.$identifier/builds/new.tsx
https://github.com/Sendouc/sendou.ink/issues/1150
Ranked Modes checkboxes are now checked by default when making a new build.
- Does not overwrite values for builds that already exist, i.e. builds that you are editing instead of attempting to create.
=> Ranked Modes checkboxes are now checked by default when making a new build

public/locales/da/analyzer.json
Fixed misspeling of the following line in the Danish analyser.json file
-   "stat.category.subDef" #fixed a missspelling of "våben"
=> Corrected Danish translation in analyzer.json

app/features/map-planner/components/Planner.tsx, app/hooks/usePlannerBg.ts, app/routes/contributions.tsx, app/utils/urls.ts, public/locales/en/contributions.json
https://github.com/Sendouc/sendou.ink/issues/1161
Implemented some dynamic background sizing & positioning calculations for the Map Planner.
This won't work well on mobile in portrait mode, since the user won't be able to access most of the controls (honestly, a user should not be attempting to use the feature in portrait mode anyway because it's impractical). It will work fine on landscape without any kind of min-sizing (as mentioned in the original issue).
- 24" monitor, full screen (1920 x 1080):
- 27" monitor, full screen (2560 x 1440):
- Pixel 5 in Landscape Mode (851 x 393):
- iPad Mini in Portrait Mode (768 x 1024):
=> Implemented some dynamic background sizing & positioning calculations for the Map Planner

app/features/build-analyzer/core/stats.ts
https://github.com/Sendouc/sendou.ink/issues/1211
Fixed long trailing decimals from displaying for Special Weapon ink consumption stats.
All I did was include the entire mathematical expression in the `roundToNDecimalPlaces()` function that already existed.
=> Fixed long trailing decimals from displaying for Special Weapon ink consumption stats

app/features/build-analyzer/core/specialEffects.test.ts, app/features/build-analyzer/core/specialEffects.ts
Change DR to give 30 AP per ability: See #1265 
Note that in my testing, DR *does* stack with normal abilities unlike Tacticooler (tested by running >30 AP of ink res alongside DR; as soon as the DR runs out you take ink damage, meaning that it does stack and doesn't simply raise it to 30 if it is less than that)
=> Fix Drop Roller AP: 30 AP per ability

app/components/layout/Footer.tsx, app/styles/layout.css
https://github.com/Sendouc/sendou.ink/issues/1276
Fixed copyright note so that it does not overlap other UI elements horizontally at high zoom levels (200% or higher).
Screenshot of the copyright notice after the change (at 200% zoom level):
=> Fixed copyright note so that it does not overlap other UI elements horizontally at high zoom levels

app/features/build-analyzer/core/stats.ts, app/utils/number.ts
Adjusts stats.ts and creates a new case for ability type, "SUB_VELOCITY", which would allow for separate processing in the future and keeps me from accidentally changing other values.
Fixes a bug in the roundToNDecimalPlaces routine in number.ts, where the previous implementation had a hard coded 2 decimal cutoff from the use of 100 instead of 10**n.
First time doing a pull request or using this javascript framework, so feel free to offer guidance or feedback.
=> Round sub velocity to thousandths place, fix bug in round function (Fixes #1348)

app/styles/common.css
Fixes #1411
After some searching, I was very lucky to find the easiest solution, which is described in this comment:
> PS Omitting the height: 100% effectively locks the scrolling at the current position without the jumping - on latest Chrome, at least. – [zerm](https://stackoverflow.com/users/359335/zerm)
https://stackoverflow.com/questions/3656592/how-to-programmatically-disable-page-scrolling-with-jquery
(I actually have no idea why it behaves like that...)
P.S. There's also a JavaScript solution but is not even close as neat: https://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily
=> Fix: page scrolls to top when opening dialog

app/routes/u.$identifier/results/index.tsx
First time creating a pull request, hope this is alright.
Single line fix, the style "items-center" was applied to the whole table, causing all the content to align to center, which caused overflow if it didnt fit the screen.
The style already gets applied to the individual list items, so removing it from the table caused no further issues.
=> Fixed #1407

app/features/object-damage-calculator/calculator.css, app/features/object-damage-calculator/routes/object-damage-calculator.tsx
I have some proposed changes for the damage calculator grid, particularly to make it more mobile friendly.
Currently you have to scroll up/down and left/right a lot, quickly loosing track of the relevant damage type and damage receiver.
On Desktop it can also sometimes not be obvious that there is more content to the right until you scroll all the way down.
By sacrificing a tiny amount of space, its possible to fit all row content on Desktop.
The first row is made sticky, so the relevant information never leaves the screen.
On mobile the first column is also made sticky.
This way you can always see which data corresponds to which damage type and damage receiver.
I tried to keep all the styling as close to the original as possible, but had to cut down on a few paddings.
Let me know what …
=> Damage Calculator Grid Rework

app/components/Main.tsx, app/components/layout/SideNav.tsx, app/components/layout/index.tsx, app/routes/calendar/index.tsx, app/styles/calendar.css, app/styles/layout.css
I noticed on the VODs page that the content clips into the sidebar before it reaches the breakpoint.
I was going to make a quick fix by adding some padding, but noticed the reason for this is that both navbar and sidebar do not take any actual space on the page due to having a fixed position.
By moving around some elements and changing them to be sticky its possible to have the same behavior while having the elements actually take up space.
This makes layouting easier and more consistent and avoids clipping. Both navbar and sidebar would also be more future proof to any changes since they can no longer mess with any page content.
It also has the added benefit of making the interaction with the footer a lot more natural!
If you look at the main content div you can see that it now respects …
=> Page layout change proposal

app/components/Pagination.tsx, app/styles/common.css
This fixes issue https://github.com/Sendouc/sendou.ink/issues/1513
Since you already applied the ``dir="rtl"`` attribute to the HTML element, we can use a CSS attribute selector to apply a style to a class only if that attribute is present.
This makes for a really simple and clean implementation. If any future RTL issues come up, you can just make your own utility class using the ``html[dir="rtl"]`` attribute selector.
=> Added rtl utility class

app/features/build-analyzer/core/weapon-params.json, app/features/object-damage-calculator/calculator-constants.ts, app/features/object-damage-calculator/core/object-dmg.json, app/features/object-damage-calculator/core/objectHitPoints.ts, app/features/object-damage-calculator/routes/object-damage-calculator.tsx, scripts/create-analyzer-json.ts
- Adds Triple Splashdown's object damage to the DMG Calc
- Makes Sprinkler's HP 120 + adds Ink Vac as a damage reciever (Closes #1555 and #1554)
=> Add/Fix miscellaneous object damage/build analyzer data

app/features/chat/chat-utils.ts, app/features/chat/components/Chat.tsx, app/features/sendouq-settings/q-settings.css, app/features/sendouq-settings/routes/q.settings.tsx
Just a simple volume slider for SQ sounds
https://github.com/Sendouc/sendou.ink/assets/101019309/d64ff875-fe02-42b3-84f4-7ad8d4c7011e
Should work on all major browsers, cant test Safari unfortunately. Firefox will fire the sound twice when testing for mobile in a desktop browser, but will work correctly when using on an actual mobile device (its always Firefox).
=> Volume slider

app/features/object-damage-calculator/calculator-constants.ts, app/features/object-damage-calculator/core/object-dmg.json, app/features/object-damage-calculator/core/objectHitPoints.ts, app/features/object-damage-calculator/routes/object-damage-calculator.tsx, scripts/create-object-dmg-json.ts
Adds damage calculations for the recycled Brella to the object damage table. The name of the brella as well as the damage calculations are taken from @lobotomysyndrome on discord as of 03/01/2024.
(Closing the first PR and creating this one to squash commits)
=> Add recycled brella damage

app/features/tournament-bracket/core/Tournament.server.ts, app/features/tournament-bracket/core/Tournament.ts, app/features/tournament-bracket/core/tests/mocks.ts, app/features/tournament-bracket/core/tests/test-utils.ts, app/features/tournament/routes/to.$id.tsx
Added Twitter's special tags. They were required for rendering because they are special.
Their docs don't mention anything about renaming `name="twitter:card"` into `name="x:tag"`, let's hope Elon doesn't notice.
Fixes https://github.com/Sendouc/sendou.ink/issues/1741
=> Added twitter's special tags

app/db/tables.ts, app/features/lfg/lfg-types.ts, app/features/lfg/routes/lfg.tsx, app/hooks/useSearchParamState.ts
This completes https://github.com/Sendouc/sendou.ink/issues/1733
Also added support for custom encoder for `useSearchParamState`, this should enable us to avoid having a big json blob on the url bar :p
Demonstration of the code working: https://testing.avillagra.net/lfg?q=l.en-w.0%2C1-mn.1
=> Added support for sharing a filter set using the URL

app/components/icons/Beaker.tsx, app/features/build-analyzer/routes/analyzer.tsx, locales/en/analyzer.json
Added an alternative title/tooltip/hover text for the `Beaker` icon to give a better hint of why it's clickable.
This is just a personal preference, feel free to close the PR if you don't like it. Technically, the same change could be applied to all icons.
1. Icon props
2. `analyzer.tsx`, pass custom title to the icon
3. Translation
=> Feat: add custom title for icon

app/db/seed/index.ts, app/features/tournament-bracket/components/MatchActionsBanPicker.tsx, app/features/tournament-bracket/core/Progression.test.ts, app/features/tournament-bracket/core/Progression.ts, app/features/tournament-bracket/core/Tournament.ts, app/features/tournament-bracket/core/tests/test-utils.ts, app/features/tournament-bracket/routes/to.$id.brackets.tsx, app/features/tournament/core/Standings.ts, app/features/tournament/routes/to.$id.results.tsx, app/features/tournament/tournament.css
Take in account more brackets than just the "main route".
Also show more matches on the results page, brackets separated.
=> Better tournament standings

app/features/tournament-bracket/components/Bracket/PlacementsTable.tsx, app/features/tournament-bracket/core/Bracket.test.ts, app/features/tournament-bracket/core/Bracket.ts, app/features/tournament-bracket/core/tests/mocks.ts
=> Adjust Round Robin & Swiss standings logic

app/features/object-damage-calculator/core/objectDamage.ts
Proposed solution to Issue #1544 
Added a special case to the "otherDamage()" function that returns 0 if the weapon is Tri-Stringer and the special is Booyah. Let me know if there are any changes I should make to the implementation, thanks!
To test, run the development build, navigate to the Damage Calculator, and select Tri-Stringer/Inkline Tri-Stringer. The intended result is 136.5 DMG and 4 HTD in the "maximum" damage type, with the others being unaffected.
=> Stringer Max Booyah Damage Fix

app/features/badges/homemade.ts
Changed the name of "Original Message Deleted" badge to "[Original Message Deleted]"
=> Changed Name of Original Message Deleted badge

app/styles/elements.css
Prevent switch from shrinking when label is too large. Just some flex weirdness, switched to grid instead.
Closes #2161
=> Fix switch styling

app/components/Pagination.tsx, app/styles/common.css
This PR updates the pagination to prevent it from overflowing weirdly with too many items
Closes #1637 
Desktop view
Mobile view remains the same
=> Prevent pagination from weird overflow

app/features/api-private/routes/patrons.ts, app/features/api-private/routes/seed.ts, app/features/api-private/routes/users.ts, app/features/api-public/routes/calendar.$year.$week.ts, app/features/api-public/routes/org.$id.ts, app/features/api-public/routes/sendouq.active-match.$userId.ts, app/features/api-public/routes/sendouq.match.$matchId.ts, app/features/api-public/routes/tournament-match.$id.ts, app/features/api-public/routes/tournament.$id.brackets.$bidx.standings.ts, app/features/api-public/routes/tournament.$id.brackets.$bidx.ts, app/features/api-public/routes/tournament.$id.casted.ts, app/features/api-public/routes/tournament.$id.teams.ts, app/features/api-public/routes/tournament.$id.ts, app/features/api-public/routes/user.$identifier.ts, app/features/front-page/routes/patrons-list.ts, app/features/leaderboards/core/leaderboards.server.ts, app/features/leaderboards/routes/leaderboards.tsx, app/features/theme/routes/theme.ts, app/root.tsx, app/utils/playwright.ts, app/utils/remix.server.ts, e2e/tournament.spec.ts, package.json, vite.config.ts
Passes tests + e2e tests.
Biggest question is performance impact. For example tournament with ID 1396 is only around 260 avg RPM throughput when the old one was 735. Might still just try it in production and see what happens.
Progress on issue http://github.com/Sendouc/sendou.ink/issues/2281
=> Single fetch future flag

app/styles/common.css
I was trying to analyze an Ink Saver only build on the [build analyzer page](https://sendou.ink/analyzer) on a phone. 
Tapping the ability button twice will zoom in the page instead of selecting the ability twice. This behavior is a bit strange and can be fixed with a [`touch-action`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) CSS rule.
=> Add CSS rule `touch-action: manipulation` to ability selector

content/articles/competitive-guidebook-part-1.md
Updating invite link for Under Pressure. The vanity URL was taken by a nsfw server recently.
=> Update Discord invite for Under Pressure in Competitive Guidebook article

app/features/api-public/routes/tournament.$id.teams.ts, app/features/api-public/schema.ts
Small change to `GET /api/tournament/{tournamentId}/teams` to expose country info. Helps in allowing TOs to pull statistics on which regions are playing in their tournaments as well as useful for pulling information for wikis like Liquipedia or Inkipedia should the community want to focus efforts in it down the line.
I didn't see any tests for the public API so apologies if there's a test I need to edit !!
=> Add player country info to teams in tourney API

content/articles/splatoon-3-na-league-event-1-preseason-1.md
Add Stronghold Article, originally posted at https://www.splatoonstronghold.com/news/splatoon-3-north-american-league-event-2-preseason-week-2
=> Add Stronghold Article "Splatoon 3 NA League Event 2 Preseason Week 2"
