- frontend-react/public/locales/pt-BR/translation.json
Signed-off-by: Guigas <jimhorton7@outlook.com>
> Fix typo on calendar page (pt-BR translation)

- frontend-react/public/locales/pt-BR/translation.json
Signed-off-by: guigas7 <jimhorton7@outlook.com>
> Adds pt-BR translation of hp and standardizes title tenses

- frontend-react/public/locales/pt-BR/translation.json
Adds x leaderboards translations and fixes tools translation to fit the box
Signed-off-by: guigas7 <jimhorton7@outlook.com>
> [portuguese] Adds x leaderboards translations and a small fix

- components/layout/Footer.tsx
> Fix squid image in light theme

- pages/u/[identifier].tsx
> Check bio length after trim()

- .github/workflows/ci.yml
I'm opening this PR as a test – I don't expect it to work first try. (Opening the PR should cause GitHub Actions to run.)
> Try out GitHub Actions

- components/common/WeaponSelector.tsx
- locale/de/messages.json
- locale/el/messages.json
- locale/en/messages.json
- locale/es/messages.json
- locale/fr/messages.json
- locale/he/messages.json
- locale/it/messages.json
- locale/ja/messages.json
- locale/ko/messages.json
- locale/nl/messages.json
- locale/pt/messages.json
- locale/ru/messages.json
- locale/sv/messages.json
> weaponSelector correct value + locales param update

- theme.ts
#347 
It solves problem now but probably in the long run there should be another solution (#298 mentions about it).
> borderColor fix

- .github/workflows/ci.yml
- .prettierignore
- package.json
- utils/i18n.ts
Part of #321. Follow-up to PR #341.
In theory, opening this PR should cause [the `ci.yml` action](https://github.com/Sendouc/sendou.ink/actions/workflows/ci.yml) to run. Then we can see whether the GitHub Action actually works! Again, I suspect this will actually fail on first try 😛 
Once this is working and all the tests are passing, the [repo settings](https://github.com/rofreg/sendou.ink/settings) can be updated such that any merge into the `main` branch requires CI to pass.
> Further testing of GitHub Actions

- app/calendar/components/CalendarPage.tsx
- app/xrank/components/XSearchPage.tsx
- app/xrank/components/XTrendsPage.tsx
- pages/analyzer.tsx
- pages/builds/[[...slug]].tsx
- pages/freeagents.tsx
- pages/itz.tsx
- pages/maps.tsx
- pages/plans.tsx
- pages/player/[id].tsx
- pages/sr/guide/[level].tsx
- pages/sr/leaderboards/index.tsx
- pages/sr/leaderboards/new.tsx
- pages/t/[team].tsx
- pages/t/index.tsx
- pages/u/[identifier].tsx
- pages/u/index.tsx
> Titles for pages

- .github/dependabot.yml
- .github/workflows/ci.yml
- .prettierignore
- package.json
Reverts #361 / re-enables most of #342.
I'm opening this PR as a starting place – we'll see how it goes! It will probably require more tweaking and testing before the GitHub Action fully passes.
> Re-enable GitHub Actions

- components/analyzer/EditableBuilds.tsx
- pages/analyzer.tsx
> Reset button for builds analyzer

- components/common/MySelect.tsx
#389 
Suggested solution works fine - can be tested in weapon and gear selectors.
> Custom filter option

- components/common/GearSelector.tsx
- components/common/MySelect.tsx
- components/common/UserSelector.tsx
- components/common/WeaponSelector.tsx
- components/sr/RotationSelector.tsx
- prisma/queries/getAllUsersLean.ts
#233 
I didn't find problems with JP characters but implemented second part of issue. Also made customFilterOption as props for MySelect (because different selectors require different logic).
> UsersSelector - search via twitter

- pages/_app.tsx
> Themed switch

- app/calendar/components/EventModal.tsx
- app/freeagents/components/FAModal.tsx
- components/u/BuildModal.tsx
- components/u/ProfileModal.tsx
- pages/maps.tsx
- pages/sr/leaderboards/new.tsx
#404 
I think form labels + controllers should be wrapped in formcontrol (with it old form labels still have margin). Probably there is another solution but this looks logical (another elements like markdowntextarea have formcontrol and form label inside - margins are working).
> Modals Spacing

- components/layout/MobileNav.tsx
#432 
Now it slides from left. Also on plans page it's placed on the left side.
> Menu left placement

- pages/about.tsx
#456 
I can do it for myself but not for Villy / 앤드류 (link leads to a non-exist twitter profile).
> Fix link in about

- components/common/MultipleModeSelector.tsx
- pages/maps.tsx
- pages/styles.css
#439 
It saves count, generation mode and custom order modes.
> Saving maplist generator settings in URL

- components/common/Markdown.tsx
#387 
Rendering div instead of p for markdown should be enough.
> Fix validateDOMNesting warning

- components/layout/Nav.tsx
- pages/styles.css
#429 
I disable scrollbar visibilty but scroll is working. Max-height probably can be changed.
> Scrollable nav

- components/common/WeaponSelector.tsx
> Search weapons by sub or special (en-only)

- components/builds/BuildFilters.tsx
- components/common/ModeImage.tsx
- components/common/MultipleModeSelector.tsx
- components/common/MySelect.tsx
- utils/selectStyles.ts
> New filters for builds page

- components/common/GearSelector.tsx
> Search by brand

- hooks/team-splitter/index.ts
> Block button by default

- components/u/BadgeContainer.tsx
> Badges multiplier near icon

- app/styles/layout.css
Fix #916 
Buttons are _tabbable_ but there were without outline.
> Outline for tabbed lang buttons

- app/routes/calendar/index.tsx
- app/styles/calendar.css
- app/styles/vars.css
Fix #943
The bug was in the divider tag: hr
fixed property: width: 50rem.
> Fix mobile layout calendar

- public/locales/da/common.json
Added missing stringfor "actions.loadMore"
The weapon categories have just been added, as there are no Danish names for the weapon categories.
> Added weapon caategory and other translations.

- public/locales/ja/analyzer.json
- public/locales/ja/common.json
- translation-progress.md
Add and Update ja translation files.
- common.json
- analyzer.json
> Add and Update ja translations.

- public/locales/fr/common.json
- translation-progress.md
Added the translation for weapons classes names.
> Update common -->FR translation

- public/locales/fr/analyzer.json
Fixed a typo and added a more accurate translation for "patch".
> Minor changes to analyzer FR

- app/styles/common.css
> Select dropdown arrow position should use fixed value instead of percent

- app/routes/analyzer.tsx
- app/styles/analyzer.css
> Stat Card values should be on the same line

- public/locales/da/common.json
Added translation for "pages.s2"
Made minor fixes for bad translations.
Added Danish translations for weapon categories.
> Adding missing translation

- app/routes/u.$identifier.tsx
Closes #903 
This seemed pretty straightforward, or am I missing something? 🙂
> Add results count to user page tab

- app/styles/plus.css
> Wrap overflowing plus comments

- app/components/layout/UserItem.tsx
- app/modules/auth/errors.ts
- app/modules/auth/index.ts
- app/modules/auth/routes.server.ts
- app/utils/urls.ts
- public/locales/de/common.json
- public/locales/en/common.json
- translation-progress.md
> Show dialog for failed login attempts

- app/components/layout/index.tsx
- app/routes/admin.tsx
- app/routes/analyzer.tsx
- app/routes/badges.tsx
- app/routes/builds.tsx
- app/routes/calendar/index.tsx
- app/routes/maps.tsx
- app/routes/plus.tsx
- app/utils/remix.ts
This PR is review-ready ~~but still pointing towards `breadcrumbs` branch, because I wanted to build on top of the setup I implemented there.
On hold until #1029 is merged or rejected.~~
Fixes #1026
> Detect active nav item via route handle instead of path matching

- app/routes/analyzer.tsx
- public/locales/en/analyzer.json
#973
Simple check for sub id + additional message
> Note about torpedo in build analyzer

- app/routes/u.$identifier/results/index.tsx
https://github.com/Sendouc/sendou.ink/issues/1068
Hide Highlights section if the user has exactly 1 result on their profile.
See the comments for more detailed screenshots
> Issue 1068:  Hide Highlights section if the user has exactly 1 result on their profile

- app/components/DateInput.tsx
- app/routes/calendar/new.tsx
- app/styles/calendar-new.css
- app/utils/dates.ts
Closes #858 (leftover task for setting hours of the initial date to :00)
Closes #1082
> Date input logic and UI improvements

- app/routes/plus/suggestions/comment.$tier.$userId.tsx
- app/routes/plus/suggestions/new.tsx
- app/utils/zod.ts
Closes #828 
Just learned about this "native" validation API, I love it :)
> Improve plus suggestion comment validation

- public/locales/ja/common.json
- public/locales/ja/front.json
Trying to catch up newly added translation items + some translation improvements (direct translation to more verbal words).
> [JA] added new translation items + minor improvements

- public/locales/ja/calendar.json
- public/locales/ja/common.json
- public/locales/ja/tournament.json
Translations should be ok, but I might correct some of them after checking Prod server's webpage.
> update translation-ja for TO 

- public/locales/zh/calendar.json
- public/locales/zh/common.json
- public/locales/zh/tournament.json
> Add Chinese translation for the TO Tool 

- scripts/generate-gear-csv.js
- scripts/generate-weapon-csv.js
https://github.com/Sendouc/sendou.ink/issues/1146
Added a script that generates a CSV containing basic attribute information on each Main Weapon
> Added a script that generates a CSV containing basic attribute information on each Main Weapon

- app/routes/object-damage-calculator.tsx
- app/styles/object-damage.css
The UI for AP has been moved  over the damage receivers that receive its effects
> Object DMG AP UI Relocated and Icons For AP Effects

- public/locales/de/analyzer.json
- public/locales/de/calendar.json
- public/locales/de/common.json
- public/locales/de/contributions.json
- public/locales/de/faq.json
- public/locales/de/tournament.json
- public/locales/de/user.json
DE localization should be at 💯 again 🥨
> Updated DE localization

- public/locales/da/common.json
Added the following translations to the common.json file. plans.bgStyle.OVER
plans.bgStyle.MINI
plans.bgStyle.ITEMS
> Added Danish tralsnation in planner.json file

- app/routes/calendar/$id/index.tsx
- public/locales/en/calendar.json
- public/locales/zh/calendar.json
This fixes issue #1311 
Using a new JSON field in `calendar.json` called `participatedPlayerCount` to alternatively show "X players participated".
Before rendering `<Results />`, a helper function checks if any team in results contains more than 1 player. If so then render `participatedCount`, else render `participatedPlayerCount`
I've tested locally with the dummy data
show players
show teams
I'm quite new to front-end development. Please let me know if this needs to be improved. Thank you.
> Fixes #1311

- public/locales/ja/builds.json
- public/locales/ja/common.json
- public/locales/ja/tournament.json
- public/locales/ja/user.json
just catching up to complete translations
> add more translated itemas 

- public/locales/fr/analyzer.json
- public/locales/fr/common.json
- public/locales/fr/faq.json
- public/locales/fr/q.json
> Update French translation

- app/components/Ability.tsx
- app/components/Chart.tsx
- app/components/Table.tsx
- app/components/icons/Beaker.tsx
- app/features/build-analyzer/analyzer.css
- app/features/build-analyzer/components/PerInkTankGrid.tsx
- app/features/build-analyzer/core/stats.ts
- app/features/build-analyzer/core/utils.ts
- app/features/build-analyzer/routes/analyzer.tsx
- app/modules/auth/DiscordStrategy.server.ts
- app/routes/calendar/$id/index.tsx
- app/routes/u.$identifier/results/components/UserResultsTable.tsx
- app/routes/u.$identifier/seasons.tsx
- app/styles/common.css
- app/styles/utils.css
- app/styles/vars.css
- public/locales/en/analyzer.json
> Build Analyzer visualizations

- app/features/vods/queries/findVods.server.ts
Fix #1298 
Hi Sendou, it's been a while since the last PR :)
The problem lies in the SQL `and vm."stageId" = coalesce(@stageId, vm."stageId")`, which filters out all the weapons that don't match with the query. I moved the logic to JavaScript since I couldn't find a better SQL to achieve the safe effect as `includes()`.
> Fix VoDs page weapon display problem

- app/features/leaderboards/core/leaderboards.server.ts
- app/features/leaderboards/routes/leaderboards.tsx
- app/features/sendouq-streams/QStreamsRepository.server.ts
- app/features/sendouq-streams/core/streams.server.ts
- app/features/sendouq-streams/q-streams-constants.ts
- app/features/sendouq-streams/routes/q.streams.count.ts
- app/features/sendouq-streams/routes/q.streams.tsx
- app/features/sendouq/components/GroupCard.tsx
- app/features/sendouq/q.css
- app/features/sendouq/routes/q.looking.tsx
- app/features/sendouq/routes/q.match.$id.tsx
- app/features/sendouq/routes/q.tsx
- app/features/tournament/routes/to.$id.streams.tsx
- app/modules/twitch/streams.ts
- app/modules/twitch/utils.ts
- app/utils/urls.ts
- public/locales/en/q.json
- remix.config.js
> SendouQ streams

- app/features/tournament/routes/to.$id.register.tsx
- app/features/tournament/routes/to.$id.tsx
- app/root.tsx
Here are a couple of screenshots of it working :D
> Added open graph tags for tournaments

- app/features/build-analyzer/analyzer-constants.ts
- app/features/object-damage-calculator/calculator-constants.ts
- app/features/object-damage-calculator/core/object-dmg.json
Object damage was redone incorrectly, missing Wellstring and Decav and showing incorrect numbers. Addresses #1755
> Fix Wellstring and Decav damage numbers

- app/db/tables.ts
- app/features/lfg/lfg-constants.ts
- locales/en/lfg.json
Very simple change, just adds a new LFG type.
Addresses #1769.
> Add "looking for individual coaching" and "looking for scrim partners" options

- README.md
> Remove outdated script example

- app/features/object-damage-calculator/calculator-constants.ts
- app/features/object-damage-calculator/core/object-dmg.json
- app/features/object-damage-calculator/core/objectHitPoints.ts
- app/features/object-damage-calculator/routes/object-damage-calculator.tsx
> Add Triple Splashdown fist as receiver to object dmg calc

- app/features/team/team-constants.ts
- locales/en/team.json
> Add sub role to team page

- app/features/sendouq/QRepository.server.ts
- app/features/sendouq/components/MemberAdder.tsx
- app/features/sendouq/routes/q.preparing.tsx
- app/features/tournament/actions/to.$id.register.server.ts
- app/features/tournament/routes/to.$id.register.tsx
- app/hooks/swr.ts
- locales/en/q.json
- locales/es-ES/q.json
- locales/es-US/q.json
- locales/ja/q.json
- locales/pt-BR/q.json
- locales/ru/q.json
- locales/zh/q.json
> Sort truster selects by team

- app/features/badges/homemade.ts
Updated the discordID to the actual artist for the badge.
> Update the authorDiscordId for Power Pair Showdown

- content/articles/A-dying-scene-Stronghold-and-Splatoon-4.md
> Stronghold Article: Update A-dying-scene-Stronghold-and-Splatoon-4.md

- app/features/info/routes/faq.module.css
- app/features/info/routes/faq.tsx
- app/features/lfg/components/LFGFilters.module.css
- app/features/lfg/components/LFGFilters.tsx
- app/features/lfg/components/LFGPost.module.css
- app/features/lfg/components/LFGPost.tsx
- app/features/lfg/routes/lfg.tsx
Convert FAQ and LFG styles to CSS modules for improved encapsulation and maintainability. Update component classes to use the new module styles.
> Refactor FAQ and LFG CSS modules

- app/features/art/actions/art.new.server.ts
- app/features/calendar/actions/calendar.new.server.ts
- app/features/calendar/loaders/calendar.new.server.ts
- app/features/img-upload/actions/upload.server.ts
- app/features/user-page/UserRepository.server.ts
- app/features/user-page/loaders/u.$identifier.edit.server.ts
- app/features/vods/actions/vods.new.server.ts
- app/features/vods/vods-utils.ts
And fix probably bug with favorite badges not reading one that takes in account user's patron status being gone
> Refactor more logic to use global roles

- app/db/tables.ts
- app/features/calendar/CalendarRepository.server.ts
- app/features/calendar/actions/calendar.new.server.ts
- app/features/calendar/calendar-schemas.ts
- app/features/calendar/routes/calendar.new.tsx
- app/features/front-page/core/ShowcaseTournaments.server.ts
- app/features/notifications/notifications-types.ts
- app/features/notifications/notifications-utils.ts
- app/features/tournament-bracket/actions/to.$id.brackets.server.ts
- app/features/tournament-bracket/components/BracketMapListDialog.tsx
- app/features/tournament-bracket/components/StartedMatch.tsx
- app/features/tournament-bracket/core/PickBan.ts
- app/features/tournament-bracket/core/Tournament.ts
- app/features/tournament-bracket/core/mapList.server.ts
- app/features/tournament-bracket/core/toMapList.ts
- app/features/tournament-bracket/routes/to.$id.matches.$mid.tsx
- app/features/tournament-bracket/tournament-bracket-schemas.server.ts
- app/features/tournament/TournamentRepository.server.ts
- app/features/tournament/actions/to.$id.admin.server.ts
- app/features/tournament/actions/to.$id.register.server.ts
- app/features/tournament/tournament-utils.ts
- app/features/tournament/tournament.css
- app/routines/notifyCheckInStart.ts
- app/styles/common.css
- app/styles/utils.css
- e2e/tournament-bracket.spec.ts
- locales/en/common.json
Closes #2193 
Closes #2162
+ counterpicking option where repicking mode is not restricted
> Test tournaments, prematch chat & counterpicking with mode repeat

- app/db/tables.ts
- app/features/sendouq-match/QMatchRepository.server.ts
- app/features/sendouq-settings/QSettingsRepository.server.ts
- app/features/sendouq-settings/q-settings-schemas.server.ts
- app/features/sendouq-settings/routes/q.settings.tsx
- app/features/sendouq/components/GroupCard.tsx
- app/features/sendouq/q-types.ts
- app/utils/zod.ts
- migrations/086-add-weapon-pool-favorites.js
This PR adds the ability to favorite weapons in the SQ weapon pool by extending the ``qWeaponPool`` column to be an object array with an ``isFavorite`` key
Closes #2275
Related Discord posts:
https://discord.com/channels/299182152161951744/1371255146155347978/1371255146155347978
https://discord.com/channels/299182152161951744/1298281446821199966/1298281446821199966
> SendouQ favorite weapons

- app/features/build-analyzer/core/weapon-params.ts
- scripts/create-analyzer-json.ts
This PR adds damage params for Splattercolor Screen and Triple Inkstrike for the damage calculator
Closes #1398
> Add tristrike and screen damage params

- app/features/badges/homemade.json
Name change,
file name: silverstars
Change display name from: Beta Bracket -> Leblanc Hideout Beta Bracket
> Rename Silver Stars badge

- app/features/tournament/core/Standings.ts
- app/utils/urls.ts
Resolves https://discord.com/channels/299182152161951744/1376207593906901083.
> Replace outdated SPR links with archive links

- app/components/Time.tsx
- app/components/TimePopover.tsx
- app/features/scrims/routes/scrims.$id.tsx
- app/features/tournament/routes/to.$id.register.tsx
- app/styles/common.css
- locales/de/common.json
- locales/en/common.json
Adds a Time component with copy to discord functionality
closes #2334
> Add a time component

- app/features/api-private/routes/patrons.ts
- app/features/api-private/routes/seed.ts
- app/features/api-private/routes/users.ts
- app/features/api-public/routes/calendar.$year.$week.ts
- app/features/api-public/routes/org.$id.ts
- app/features/api-public/routes/sendouq.active-match.$userId.ts
- app/features/api-public/routes/sendouq.match.$matchId.ts
- app/features/api-public/routes/tournament-match.$id.ts
- app/features/api-public/routes/tournament.$id.brackets.$bidx.standings.ts
- app/features/api-public/routes/tournament.$id.brackets.$bidx.ts
- app/features/api-public/routes/tournament.$id.casted.ts
- app/features/api-public/routes/tournament.$id.teams.ts
- app/features/api-public/routes/tournament.$id.ts
- app/features/api-public/routes/user.$identifier.ts
- app/features/front-page/routes/patrons-list.ts
- app/features/leaderboards/core/leaderboards.server.ts
- app/features/leaderboards/routes/leaderboards.tsx
- app/features/theme/routes/theme.ts
- app/root.tsx
- app/utils/playwright.ts
- app/utils/remix.server.ts
- e2e/tournament.spec.ts
- package.json
- vite.config.ts
Seems to cause a memory leak or something?
> Revert "Single fetch future flag (#2348)"

- content/articles/ipl-x-area-cup-splat-world-series.md
Reposting the Splatoon Stronghold article: https://splatoonstronghold.squarespace.com/news/ipl-x-area-cup-splat-world-series. Please and thank you
> Stronghold Article: IPL x AREA CUP: Splat Word Series

- app/features/sendouq/routes/q.info.tsx
- app/features/sendouq/routes/q.rules.tsx
hiya sendou  i made this quick little mock up of an updated rules pages, i feel like the rules page dose not have exactly all the info and sometimes the wording can be a bit weird so BAM! updated rules lmk if you want any changes or are even considering the change at all :D
(btw changed the info page to reflect the $500 cash prize instead of $750 im pretty sure you said this in this https://bsky.app/profile/sendou.ink/post/3lrllpzafe22h tweet) 
😎
> Rules Clarification / Updates (+ quick info page update)

- app/components/GearSelect.tsx
- app/components/WeaponSelect.module.css
- app/components/WeaponSelect.tsx
- app/components/elements/Select.module.css
- app/components/elements/Select.tsx
- app/features/leaderboards/LeaderboardRepository.server.ts
- app/features/user-page/loaders/u.$identifier.seasons.server.ts
- app/features/user-page/routes/u.$identifier.seasons.tsx
- app/styles/u.css
- locales/da/user.json
- locales/de/user.json
- locales/en/user.json
- locales/es-ES/user.json
- locales/es-US/user.json
- locales/fr-CA/user.json
- locales/fr-EU/user.json
- locales/he/user.json
- locales/it/user.json
- locales/ja/user.json
- locales/ko/user.json
- locales/nl/user.json
- locales/pl/user.json
- locales/pt-BR/user.json
- locales/ru/user.json
- locales/zh/user.json
> User page seasons links as select

- content/articles/series-weapon-power-breakdown.md
Please add Stronghold Article Series Weapon Power Breakdown.
> Stronghold Article: Series Weapon Power Breakdown

- app/features/badges/homemade.json
could you change badge names plz
"MIKU MIKU BEAM!!! Teto Takeover!" -> "MIKU MIKU BEAM!!! Grand Stage"
"5 Unique Curse of Excalibur Events" -> "Curse of Excalibur Special Events"
thanks you :D
> Badge name change

- content/articles/range-players-harmony.md
Please add article from Splatoon Stronghold site.
> Stronghold Article: range-players-harmony.md

- content/articles/qualifier-1-the-road-to-splat-world-series.md
Add article from Splatoon Stronghold.
> Stronghold Article: Qualifier 1 - The Road To Splat World Series

- content/articles/updated-directory.md
Add article from Splatoon Stronghold: https://www.splatoonstronghold.com/news/updated-directory
> Stronghold Article: Updated Directory!

- content/articles/splat-world-series-finals.md
Create Splatoon Stronghold article, originally posted at https://www.splatoonstronghold.com/news/splat-world-series-finals
> Stronghold Article: Splat World Series - Finals

- content/articles/nintendo-sponsorship-brings-splatoon-3-to-80000-students.md
Create Splatoon Stronghold article; repost of [https://www.splatoonstronghold.com/news/nintendo-sponsorship-brings-splatoon-3-to-80000-students](https://www.splatoonstronghold.com/news/nintendo-sponsorship-brings-splatoon-3-to-80000-students)
> Create Stronghold Article nintendo-sponsorship-brings-splatoon-3-to-80000-students.md

- content/articles/upcoming-major-splatoon-3-fall-tournaments.md
Add Splatoon Stronghold article; repost of https://www.splatoonstronghold.com/news/upcoming-major-splatoon-3-fall-tournaments
> Stronghold Article: Upcoming Major Splatoon 3 Fall Tournaments

- content/articles/the-splatoon-3-north-american-league-news-drop.md
Add Splatoon Stronghold article; originally posted at https://www.splatoonstronghold.com/news/the-splatoon-3-north-american-league-news-drop
> Create Stronghold Article "Splatoon 3 NA League News Drop"

- content/articles/splatoon-3-north-american-league-event-1-preseason-week-1.md
Add article from Splatoon Stronghold; "Splatoon 3 North American League Event #1 (Preseason Week 1)", repost of https://www.splatoonstronghold.com/news/splatoon-3-north-american-league-event-1-preseason-week-1
> Stronghold Article "Splatoon 3 NA League Event 1 (Preseason 1)"

- content/articles/the-splatoon-peer-review-server.md
Add article from Splatoon Stronghold: "The Splatoon Peer Review Server: A Catalyst for the Scene's Growth", repost of https://www.splatoonstronghold.com/guides/the-splatoon-peer-review-server
> Stronghold Article: "The Splatoon Peer Review Server" 

- app/features/badges/homemade.json
Updated name for Florida Collegiate event badge as i was requested
let me know if i need to do anything else :)
> Updating Name of Florida Collegiate badge
